language: python
sudo: required
dist: bionic
python: 3.7
env:
  - TOXENV=py37
  - TOXENV=style
  - TOXENV=docs
before_install:
  # Install tor and chutney if doing functional tests
  - if [[ $TEST == 'functional' ]]; then ./test/scripts/install-tor.sh; fi
  - if [[ $TEST == 'functional' ]]; then source test/scripts/install-chutney-v2.sh; fi
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
